name: Deploy Student Registration App

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build \
          -t ${{ steps.login-ecr.outputs.registry }}/student-backend:latest \
          ./backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t ${{ steps.login-ecr.outputs.registry }}/student-frontend:latest \
          ./frontend

      - name: Push Backend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/student-backend:latest

      - name: Push Frontend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/student-frontend:latest

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/student-backend:latest
          severity: CRITICAL
          ignore-unfixed: true

      - name: Copy Docker Compose File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "docker/docker-compose.ec2.yml"
          target: "/home/ubuntu"
          strip_components: 1

      - name: Deploy To EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |

            aws ecr get-login-password \
            --region ${{ secrets.AWS_REGION }} | \
            sudo docker login \
            --username AWS \
            --password-stdin \
            ${{ steps.login-ecr.outputs.registry }}

            sudo docker pull \
            ${{ steps.login-ecr.outputs.registry }}/student-backend:latest

            sudo docker pull \
            ${{ steps.login-ecr.outputs.registry }}/student-frontend:latest

            sudo docker compose \
            -f /home/ubuntu/docker-compose.ec2.yml \
            down || true

            sudo docker compose \
            -f /home/ubuntu/docker-compose.ec2.yml \
            up -d

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker ps

      - name: Show URL
        run: |
          echo "Application deployed successfully"
          echo "http://${{ secrets.EC2_IP }}"
